version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
      RABBITMQ_MANAGEMENT_BIND_IP: 0.0.0.0
